server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri:

  rabbitmq:
    host: 192.168.2.107
management: #暴露出发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh