server:
  port: 9002
spring:
  application:
    name: tensquare_recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_recruit?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
